// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/service/delivery (interfaces: deliveryRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_delivery_repository.go -package=mocks . deliveryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	delivery "service-courier/internal/entity/delivery"

	gomock "go.uber.org/mock/gomock"
)

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// CreateDelivery mocks base method.
func (m *MockdeliveryRepository) CreateDelivery(ctx context.Context, d *delivery.DeliveryCreate) (*delivery.DeliveryGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDelivery", ctx, d)
	ret0, _ := ret[0].(*delivery.DeliveryGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDelivery indicates an expected call of CreateDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) CreateDelivery(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).CreateDelivery), ctx, d)
}

// DeleteDelivery mocks base method.
func (m *MockdeliveryRepository) DeleteDelivery(ctx context.Context, orderID *delivery.DeliveryOrderID) (*delivery.DeliveryGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDelivery", ctx, orderID)
	ret0, _ := ret[0].(*delivery.DeliveryGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDelivery indicates an expected call of DeleteDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) DeleteDelivery(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).DeleteDelivery), ctx, orderID)
}

// RecheckDelivery mocks base method.
func (m *MockdeliveryRepository) RecheckDelivery(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecheckDelivery", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecheckDelivery indicates an expected call of RecheckDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) RecheckDelivery(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecheckDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).RecheckDelivery), ctx)
}
