// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/service/delivery (interfaces: TxManagerDo)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_txmanager_do.go -package=mocks . TxManagerDo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTxManagerDo is a mock of TxManagerDo interface.
type MockTxManagerDo struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerDoMockRecorder
	isgomock struct{}
}

// MockTxManagerDoMockRecorder is the mock recorder for MockTxManagerDo.
type MockTxManagerDoMockRecorder struct {
	mock *MockTxManagerDo
}

// NewMockTxManagerDo creates a new mock instance.
func NewMockTxManagerDo(ctrl *gomock.Controller) *MockTxManagerDo {
	mock := &MockTxManagerDo{ctrl: ctrl}
	mock.recorder = &MockTxManagerDoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManagerDo) EXPECT() *MockTxManagerDoMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTxManagerDo) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTxManagerDoMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTxManagerDo)(nil).Do), ctx, fn)
}
