// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/service/delivery (interfaces: courierRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_courier_repository.go -package=mocks . courierRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	courier "service-courier/internal/entity/courier"

	gomock "go.uber.org/mock/gomock"
)

// MockcourierRepository is a mock of courierRepository interface.
type MockcourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourierRepositoryMockRecorder
	isgomock struct{}
}

// MockcourierRepositoryMockRecorder is the mock recorder for MockcourierRepository.
type MockcourierRepositoryMockRecorder struct {
	mock *MockcourierRepository
}

// NewMockcourierRepository creates a new mock instance.
func NewMockcourierRepository(ctrl *gomock.Controller) *MockcourierRepository {
	mock := &MockcourierRepository{ctrl: ctrl}
	mock.recorder = &MockcourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierRepository) EXPECT() *MockcourierRepositoryMockRecorder {
	return m.recorder
}

// GetAvailable mocks base method.
func (m *MockcourierRepository) GetAvailable(ctx context.Context) (*courier.CourierGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailable", ctx)
	ret0, _ := ret[0].(*courier.CourierGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailable indicates an expected call of GetAvailable.
func (mr *MockcourierRepositoryMockRecorder) GetAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).GetAvailable), ctx)
}

// SetAvailable mocks base method.
func (m *MockcourierRepository) SetAvailable(ctx context.Context, courierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAvailable", ctx, courierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAvailable indicates an expected call of SetAvailable.
func (mr *MockcourierRepositoryMockRecorder) SetAvailable(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).SetAvailable), ctx, courierID)
}

// SetBusy mocks base method.
func (m *MockcourierRepository) SetBusy(ctx context.Context, courierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBusy", ctx, courierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBusy indicates an expected call of SetBusy.
func (mr *MockcourierRepositoryMockRecorder) SetBusy(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBusy", reflect.TypeOf((*MockcourierRepository)(nil).SetBusy), ctx, courierID)
}
