// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks_test.go -package=delivery_test
//

// Package delivery_test is a generated GoMock package.
package delivery_test

import (
	context "context"
	reflect "reflect"
	delivery "service-courier/internal/entity/delivery"

	gomock "go.uber.org/mock/gomock"
)

// MockdeliveryService is a mock of deliveryService interface.
type MockdeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryServiceMockRecorder
	isgomock struct{}
}

// MockdeliveryServiceMockRecorder is the mock recorder for MockdeliveryService.
type MockdeliveryServiceMockRecorder struct {
	mock *MockdeliveryService
}

// NewMockdeliveryService creates a new mock instance.
func NewMockdeliveryService(ctrl *gomock.Controller) *MockdeliveryService {
	mock := &MockdeliveryService{ctrl: ctrl}
	mock.recorder = &MockdeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryService) EXPECT() *MockdeliveryServiceMockRecorder {
	return m.recorder
}

// DeliveryAssign mocks base method.
func (m *MockdeliveryService) DeliveryAssign(ctx context.Context, orderID *delivery.DeliveryOrderID) (*delivery.DeliveryAssign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliveryAssign", ctx, orderID)
	ret0, _ := ret[0].(*delivery.DeliveryAssign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeliveryAssign indicates an expected call of DeliveryAssign.
func (mr *MockdeliveryServiceMockRecorder) DeliveryAssign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliveryAssign", reflect.TypeOf((*MockdeliveryService)(nil).DeliveryAssign), ctx, orderID)
}

// DeliveryCheck mocks base method.
func (m *MockdeliveryService) DeliveryCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliveryCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeliveryCheck indicates an expected call of DeliveryCheck.
func (mr *MockdeliveryServiceMockRecorder) DeliveryCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliveryCheck", reflect.TypeOf((*MockdeliveryService)(nil).DeliveryCheck), ctx)
}

// DeliveryUnassign mocks base method.
func (m *MockdeliveryService) DeliveryUnassign(ctx context.Context, orderID *delivery.DeliveryOrderID) (*delivery.DeliveryUnassign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeliveryUnassign", ctx, orderID)
	ret0, _ := ret[0].(*delivery.DeliveryUnassign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeliveryUnassign indicates an expected call of DeliveryUnassign.
func (mr *MockdeliveryServiceMockRecorder) DeliveryUnassign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeliveryUnassign", reflect.TypeOf((*MockdeliveryService)(nil).DeliveryUnassign), ctx, orderID)
}
