// Code generated by MockGen. DO NOT EDIT.
// Source: ./contract.go
//
// Generated by this command:
//
//	mockgen -source=./contract.go -destination=./mocks_test.go -package=ordergrpc_test
//

// Package ordergrpc_test is a generated GoMock package.
package ordergrpc_test

import (
	context "context"
	reflect "reflect"
	orderpb "service-courier/internal/proto/orderpb"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockorderClient is a mock of orderClient interface.
type MockorderClient struct {
	ctrl     *gomock.Controller
	recorder *MockorderClientMockRecorder
	isgomock struct{}
}

// MockorderClientMockRecorder is the mock recorder for MockorderClient.
type MockorderClientMockRecorder struct {
	mock *MockorderClient
}

// NewMockorderClient creates a new mock instance.
func NewMockorderClient(ctrl *gomock.Controller) *MockorderClient {
	mock := &MockorderClient{ctrl: ctrl}
	mock.recorder = &MockorderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderClient) EXPECT() *MockorderClientMockRecorder {
	return m.recorder
}

// GetOrderById mocks base method.
func (m *MockorderClient) GetOrderById(ctx context.Context, in *orderpb.GetOrderByIdRequest, opts ...grpc.CallOption) (*orderpb.GetOrderByIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderById", varargs...)
	ret0, _ := ret[0].(*orderpb.GetOrderByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderById indicates an expected call of GetOrderById.
func (mr *MockorderClientMockRecorder) GetOrderById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderById", reflect.TypeOf((*MockorderClient)(nil).GetOrderById), varargs...)
}

// GetOrders mocks base method.
func (m *MockorderClient) GetOrders(ctx context.Context, in *orderpb.GetOrdersRequest, opts ...grpc.CallOption) (*orderpb.GetOrdersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrders", varargs...)
	ret0, _ := ret[0].(*orderpb.GetOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockorderClientMockRecorder) GetOrders(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockorderClient)(nil).GetOrders), varargs...)
}
