// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks_test.go -package=deliveryhttp_test
//

// Package deliveryhttp_test is a generated GoMock package.
package deliveryhttp_test

import (
	context "context"
	reflect "reflect"
	delivery "service-courier/internal/domain/delivery"

	gomock "go.uber.org/mock/gomock"
)

// MockdeliveryService is a mock of deliveryService interface.
type MockdeliveryService struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryServiceMockRecorder
	isgomock struct{}
}

// MockdeliveryServiceMockRecorder is the mock recorder for MockdeliveryService.
type MockdeliveryServiceMockRecorder struct {
	mock *MockdeliveryService
}

// NewMockdeliveryService creates a new mock instance.
func NewMockdeliveryService(ctrl *gomock.Controller) *MockdeliveryService {
	mock := &MockdeliveryService{ctrl: ctrl}
	mock.recorder = &MockdeliveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryService) EXPECT() *MockdeliveryServiceMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockdeliveryService) Assign(ctx context.Context, orderID delivery.OrderID) (*delivery.AssignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, orderID)
	ret0, _ := ret[0].(*delivery.AssignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockdeliveryServiceMockRecorder) Assign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockdeliveryService)(nil).Assign), ctx, orderID)
}

// CheckDelivery mocks base method.
func (m *MockdeliveryService) CheckDelivery(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDelivery", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckDelivery indicates an expected call of CheckDelivery.
func (mr *MockdeliveryServiceMockRecorder) CheckDelivery(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDelivery", reflect.TypeOf((*MockdeliveryService)(nil).CheckDelivery), ctx)
}

// Unassign mocks base method.
func (m *MockdeliveryService) Unassign(ctx context.Context, orderID delivery.OrderID) (*delivery.UnassignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", ctx, orderID)
	ret0, _ := ret[0].(*delivery.UnassignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unassign indicates an expected call of Unassign.
func (mr *MockdeliveryServiceMockRecorder) Unassign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockdeliveryService)(nil).Unassign), ctx, orderID)
}
