// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks_test.go -package=courier_test
//

// Package courier_test is a generated GoMock package.
package courier_test

import (
	context "context"
	reflect "reflect"
	courier "service-courier/internal/entity/courier"

	gomock "go.uber.org/mock/gomock"
)

// MockcourierService is a mock of courierService interface.
type MockcourierService struct {
	ctrl     *gomock.Controller
	recorder *MockcourierServiceMockRecorder
	isgomock struct{}
}

// MockcourierServiceMockRecorder is the mock recorder for MockcourierService.
type MockcourierServiceMockRecorder struct {
	mock *MockcourierService
}

// NewMockcourierService creates a new mock instance.
func NewMockcourierService(ctrl *gomock.Controller) *MockcourierService {
	mock := &MockcourierService{ctrl: ctrl}
	mock.recorder = &MockcourierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierService) EXPECT() *MockcourierServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcourierService) Create(ctx context.Context, c *courier.CourierCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockcourierServiceMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcourierService)(nil).Create), ctx, c)
}

// GetByID mocks base method.
func (m *MockcourierService) GetByID(ctx context.Context, id int) (*courier.CourierGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*courier.CourierGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockcourierServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockcourierService)(nil).GetByID), ctx, id)
}

// GetMulti mocks base method.
func (m *MockcourierService) GetMulti(ctx context.Context) ([]courier.CourierGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", ctx)
	ret0, _ := ret[0].([]courier.CourierGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockcourierServiceMockRecorder) GetMulti(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockcourierService)(nil).GetMulti), ctx)
}

// Update mocks base method.
func (m *MockcourierService) Update(ctx context.Context, c *courier.CourierUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockcourierServiceMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockcourierService)(nil).Update), ctx, c)
}
