// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks_test.go -package=courierapp_test
//

// Package courierapp_test is a generated GoMock package.
package courierapp_test

import (
	context "context"
	reflect "reflect"

	courier "github.com/shft1/service-courier/internal/domain/courier"

	gomock "go.uber.org/mock/gomock"
)

// MockcourierRepository is a mock of courierRepository interface.
type MockcourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourierRepositoryMockRecorder
	isgomock struct{}
}

// MockcourierRepositoryMockRecorder is the mock recorder for MockcourierRepository.
type MockcourierRepositoryMockRecorder struct {
	mock *MockcourierRepository
}

// NewMockcourierRepository creates a new mock instance.
func NewMockcourierRepository(ctrl *gomock.Controller) *MockcourierRepository {
	mock := &MockcourierRepository{ctrl: ctrl}
	mock.recorder = &MockcourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierRepository) EXPECT() *MockcourierRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcourierRepository) Create(ctx context.Context, cour *courier.CourierCreate) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cour)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockcourierRepositoryMockRecorder) Create(ctx, cour any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcourierRepository)(nil).Create), ctx, cour)
}

// GetAvailable mocks base method.
func (m *MockcourierRepository) GetAvailable(ctx context.Context) (*courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailable", ctx)
	ret0, _ := ret[0].(*courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailable indicates an expected call of GetAvailable.
func (mr *MockcourierRepositoryMockRecorder) GetAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).GetAvailable), ctx)
}

// GetByID mocks base method.
func (m *MockcourierRepository) GetByID(ctx context.Context, id int64) (*courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockcourierRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockcourierRepository)(nil).GetByID), ctx, id)
}

// GetMulti mocks base method.
func (m *MockcourierRepository) GetMulti(ctx context.Context) ([]courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", ctx)
	ret0, _ := ret[0].([]courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockcourierRepositoryMockRecorder) GetMulti(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockcourierRepository)(nil).GetMulti), ctx)
}

// ReleaseStaleBusy mocks base method.
func (m *MockcourierRepository) ReleaseStaleBusy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseStaleBusy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseStaleBusy indicates an expected call of ReleaseStaleBusy.
func (mr *MockcourierRepositoryMockRecorder) ReleaseStaleBusy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseStaleBusy", reflect.TypeOf((*MockcourierRepository)(nil).ReleaseStaleBusy), ctx)
}

// SetAvailable mocks base method.
func (m *MockcourierRepository) SetAvailable(ctx context.Context, courierID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAvailable", ctx, courierID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAvailable indicates an expected call of SetAvailable.
func (mr *MockcourierRepositoryMockRecorder) SetAvailable(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).SetAvailable), ctx, courierID)
}

// SetBusy mocks base method.
func (m *MockcourierRepository) SetBusy(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBusy", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBusy indicates an expected call of SetBusy.
func (mr *MockcourierRepositoryMockRecorder) SetBusy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBusy", reflect.TypeOf((*MockcourierRepository)(nil).SetBusy), ctx, id)
}

// Update mocks base method.
func (m *MockcourierRepository) Update(ctx context.Context, cour *courier.CourierUpdate) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cour)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockcourierRepositoryMockRecorder) Update(ctx, cour any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockcourierRepository)(nil).Update), ctx, cour)
}
