// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks_test.go -package=delivery_test
//

// Package delivery_test is a generated GoMock package.
package delivery_test

import (
	context "context"
	reflect "reflect"
	courier "service-courier/internal/entity/courier"
	delivery "service-courier/internal/entity/delivery"

	gomock "go.uber.org/mock/gomock"
)

// MockTxManagerDo is a mock of TxManagerDo interface.
type MockTxManagerDo struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerDoMockRecorder
	isgomock struct{}
}

// MockTxManagerDoMockRecorder is the mock recorder for MockTxManagerDo.
type MockTxManagerDoMockRecorder struct {
	mock *MockTxManagerDo
}

// NewMockTxManagerDo creates a new mock instance.
func NewMockTxManagerDo(ctrl *gomock.Controller) *MockTxManagerDo {
	mock := &MockTxManagerDo{ctrl: ctrl}
	mock.recorder = &MockTxManagerDoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManagerDo) EXPECT() *MockTxManagerDoMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTxManagerDo) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTxManagerDoMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTxManagerDo)(nil).Do), ctx, fn)
}

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// CreateDelivery mocks base method.
func (m *MockdeliveryRepository) CreateDelivery(ctx context.Context, d *delivery.DeliveryCreate) (*delivery.DeliveryGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDelivery", ctx, d)
	ret0, _ := ret[0].(*delivery.DeliveryGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDelivery indicates an expected call of CreateDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) CreateDelivery(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).CreateDelivery), ctx, d)
}

// DeleteDelivery mocks base method.
func (m *MockdeliveryRepository) DeleteDelivery(ctx context.Context, orderID *delivery.DeliveryOrderID) (*delivery.DeliveryGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDelivery", ctx, orderID)
	ret0, _ := ret[0].(*delivery.DeliveryGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDelivery indicates an expected call of DeleteDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) DeleteDelivery(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).DeleteDelivery), ctx, orderID)
}

// RecheckDelivery mocks base method.
func (m *MockdeliveryRepository) RecheckDelivery(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecheckDelivery", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecheckDelivery indicates an expected call of RecheckDelivery.
func (mr *MockdeliveryRepositoryMockRecorder) RecheckDelivery(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecheckDelivery", reflect.TypeOf((*MockdeliveryRepository)(nil).RecheckDelivery), ctx)
}

// MockcourierRepository is a mock of courierRepository interface.
type MockcourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourierRepositoryMockRecorder
	isgomock struct{}
}

// MockcourierRepositoryMockRecorder is the mock recorder for MockcourierRepository.
type MockcourierRepositoryMockRecorder struct {
	mock *MockcourierRepository
}

// NewMockcourierRepository creates a new mock instance.
func NewMockcourierRepository(ctrl *gomock.Controller) *MockcourierRepository {
	mock := &MockcourierRepository{ctrl: ctrl}
	mock.recorder = &MockcourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierRepository) EXPECT() *MockcourierRepositoryMockRecorder {
	return m.recorder
}

// GetAvailable mocks base method.
func (m *MockcourierRepository) GetAvailable(ctx context.Context) (*courier.CourierGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailable", ctx)
	ret0, _ := ret[0].(*courier.CourierGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailable indicates an expected call of GetAvailable.
func (mr *MockcourierRepositoryMockRecorder) GetAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).GetAvailable), ctx)
}

// SetAvailable mocks base method.
func (m *MockcourierRepository) SetAvailable(ctx context.Context, courierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAvailable", ctx, courierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAvailable indicates an expected call of SetAvailable.
func (mr *MockcourierRepositoryMockRecorder) SetAvailable(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).SetAvailable), ctx, courierID)
}

// SetBusy mocks base method.
func (m *MockcourierRepository) SetBusy(ctx context.Context, courierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBusy", ctx, courierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBusy indicates an expected call of SetBusy.
func (mr *MockcourierRepositoryMockRecorder) SetBusy(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBusy", reflect.TypeOf((*MockcourierRepository)(nil).SetBusy), ctx, courierID)
}
