// Code generated by MockGen. DO NOT EDIT.
// Source: service-courier/internal/service/courier (interfaces: courierRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_courier_repository.go -package=mocks . courierRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	courier "service-courier/internal/entity/courier"

	gomock "go.uber.org/mock/gomock"
)

// MockcourierRepository is a mock of courierRepository interface.
type MockcourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourierRepositoryMockRecorder
	isgomock struct{}
}

// MockcourierRepositoryMockRecorder is the mock recorder for MockcourierRepository.
type MockcourierRepositoryMockRecorder struct {
	mock *MockcourierRepository
}

// NewMockcourierRepository creates a new mock instance.
func NewMockcourierRepository(ctrl *gomock.Controller) *MockcourierRepository {
	mock := &MockcourierRepository{ctrl: ctrl}
	mock.recorder = &MockcourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierRepository) EXPECT() *MockcourierRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcourierRepository) Create(ctx context.Context, c *courier.CourierCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockcourierRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcourierRepository)(nil).Create), ctx, c)
}

// GetAvailable mocks base method.
func (m *MockcourierRepository) GetAvailable(ctx context.Context) (*courier.CourierGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailable", ctx)
	ret0, _ := ret[0].(*courier.CourierGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailable indicates an expected call of GetAvailable.
func (mr *MockcourierRepositoryMockRecorder) GetAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).GetAvailable), ctx)
}

// GetByID mocks base method.
func (m *MockcourierRepository) GetByID(ctx context.Context, id int) (*courier.CourierGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*courier.CourierGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockcourierRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockcourierRepository)(nil).GetByID), ctx, id)
}

// GetMulti mocks base method.
func (m *MockcourierRepository) GetMulti(ctx context.Context) ([]courier.CourierGet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMulti", ctx)
	ret0, _ := ret[0].([]courier.CourierGet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMulti indicates an expected call of GetMulti.
func (mr *MockcourierRepositoryMockRecorder) GetMulti(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMulti", reflect.TypeOf((*MockcourierRepository)(nil).GetMulti), ctx)
}

// SetAvailable mocks base method.
func (m *MockcourierRepository) SetAvailable(ctx context.Context, courierID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAvailable", ctx, courierID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAvailable indicates an expected call of SetAvailable.
func (mr *MockcourierRepositoryMockRecorder) SetAvailable(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).SetAvailable), ctx, courierID)
}

// SetBusy mocks base method.
func (m *MockcourierRepository) SetBusy(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBusy", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBusy indicates an expected call of SetBusy.
func (mr *MockcourierRepositoryMockRecorder) SetBusy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBusy", reflect.TypeOf((*MockcourierRepository)(nil).SetBusy), ctx, id)
}

// Update mocks base method.
func (m *MockcourierRepository) Update(ctx context.Context, c *courier.CourierUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockcourierRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockcourierRepository)(nil).Update), ctx, c)
}
