// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks_test.go -package=deliveryapp_test
//

// Package deliveryapp_test is a generated GoMock package.
package deliveryapp_test

import (
	context "context"
	reflect "reflect"
	courier "service-courier/internal/domain/courier"
	delivery "service-courier/internal/domain/delivery"
	order "service-courier/internal/domain/order"
	deliveryapp "service-courier/internal/service/deliveryapp"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockdeliveryRepository is a mock of deliveryRepository interface.
type MockdeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockdeliveryRepositoryMockRecorder is the mock recorder for MockdeliveryRepository.
type MockdeliveryRepositoryMockRecorder struct {
	mock *MockdeliveryRepository
}

// NewMockdeliveryRepository creates a new mock instance.
func NewMockdeliveryRepository(ctrl *gomock.Controller) *MockdeliveryRepository {
	mock := &MockdeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockdeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryRepository) EXPECT() *MockdeliveryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockdeliveryRepository) Create(ctx context.Context, del *delivery.AssignCreate) (*delivery.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, del)
	ret0, _ := ret[0].(*delivery.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockdeliveryRepositoryMockRecorder) Create(ctx, del any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockdeliveryRepository)(nil).Create), ctx, del)
}

// Delete mocks base method.
func (m *MockdeliveryRepository) Delete(ctx context.Context, orderID order.OrderID) (*delivery.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orderID)
	ret0, _ := ret[0].(*delivery.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockdeliveryRepositoryMockRecorder) Delete(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockdeliveryRepository)(nil).Delete), ctx, orderID)
}

// Get mocks base method.
func (m *MockdeliveryRepository) Get(ctx context.Context, orderID order.OrderID) (*delivery.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, orderID)
	ret0, _ := ret[0].(*delivery.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockdeliveryRepositoryMockRecorder) Get(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockdeliveryRepository)(nil).Get), ctx, orderID)
}

// MockcourierRepository is a mock of courierRepository interface.
type MockcourierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourierRepositoryMockRecorder
	isgomock struct{}
}

// MockcourierRepositoryMockRecorder is the mock recorder for MockcourierRepository.
type MockcourierRepositoryMockRecorder struct {
	mock *MockcourierRepository
}

// NewMockcourierRepository creates a new mock instance.
func NewMockcourierRepository(ctrl *gomock.Controller) *MockcourierRepository {
	mock := &MockcourierRepository{ctrl: ctrl}
	mock.recorder = &MockcourierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourierRepository) EXPECT() *MockcourierRepositoryMockRecorder {
	return m.recorder
}

// GetAvailable mocks base method.
func (m *MockcourierRepository) GetAvailable(ctx context.Context) (*courier.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailable", ctx)
	ret0, _ := ret[0].(*courier.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailable indicates an expected call of GetAvailable.
func (mr *MockcourierRepositoryMockRecorder) GetAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).GetAvailable), ctx)
}

// ReleaseStaleBusy mocks base method.
func (m *MockcourierRepository) ReleaseStaleBusy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseStaleBusy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseStaleBusy indicates an expected call of ReleaseStaleBusy.
func (mr *MockcourierRepositoryMockRecorder) ReleaseStaleBusy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseStaleBusy", reflect.TypeOf((*MockcourierRepository)(nil).ReleaseStaleBusy), ctx)
}

// SetAvailable mocks base method.
func (m *MockcourierRepository) SetAvailable(ctx context.Context, courierID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAvailable", ctx, courierID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAvailable indicates an expected call of SetAvailable.
func (mr *MockcourierRepositoryMockRecorder) SetAvailable(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAvailable", reflect.TypeOf((*MockcourierRepository)(nil).SetAvailable), ctx, courierID)
}

// SetBusy mocks base method.
func (m *MockcourierRepository) SetBusy(ctx context.Context, courierID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBusy", ctx, courierID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetBusy indicates an expected call of SetBusy.
func (mr *MockcourierRepositoryMockRecorder) SetBusy(ctx, courierID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBusy", reflect.TypeOf((*MockcourierRepository)(nil).SetBusy), ctx, courierID)
}

// MocktxManagerDo is a mock of txManagerDo interface.
type MocktxManagerDo struct {
	ctrl     *gomock.Controller
	recorder *MocktxManagerDoMockRecorder
	isgomock struct{}
}

// MocktxManagerDoMockRecorder is the mock recorder for MocktxManagerDo.
type MocktxManagerDoMockRecorder struct {
	mock *MocktxManagerDo
}

// NewMocktxManagerDo creates a new mock instance.
func NewMocktxManagerDo(ctrl *gomock.Controller) *MocktxManagerDo {
	mock := &MocktxManagerDo{ctrl: ctrl}
	mock.recorder = &MocktxManagerDoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktxManagerDo) EXPECT() *MocktxManagerDoMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MocktxManagerDo) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MocktxManagerDoMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MocktxManagerDo)(nil).Do), ctx, fn)
}

// MocktimeCalculatorFactory is a mock of timeCalculatorFactory interface.
type MocktimeCalculatorFactory struct {
	ctrl     *gomock.Controller
	recorder *MocktimeCalculatorFactoryMockRecorder
	isgomock struct{}
}

// MocktimeCalculatorFactoryMockRecorder is the mock recorder for MocktimeCalculatorFactory.
type MocktimeCalculatorFactoryMockRecorder struct {
	mock *MocktimeCalculatorFactory
}

// NewMocktimeCalculatorFactory creates a new mock instance.
func NewMocktimeCalculatorFactory(ctrl *gomock.Controller) *MocktimeCalculatorFactory {
	mock := &MocktimeCalculatorFactory{ctrl: ctrl}
	mock.recorder = &MocktimeCalculatorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktimeCalculatorFactory) EXPECT() *MocktimeCalculatorFactoryMockRecorder {
	return m.recorder
}

// GetDeliveryCalculator mocks base method.
func (m *MocktimeCalculatorFactory) GetDeliveryCalculator(transportType string) (deliveryapp.TimeCalculator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryCalculator", transportType)
	ret0, _ := ret[0].(deliveryapp.TimeCalculator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveryCalculator indicates an expected call of GetDeliveryCalculator.
func (mr *MocktimeCalculatorFactoryMockRecorder) GetDeliveryCalculator(transportType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryCalculator", reflect.TypeOf((*MocktimeCalculatorFactory)(nil).GetDeliveryCalculator), transportType)
}

// MockTimeCalculator is a mock of TimeCalculator interface.
type MockTimeCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockTimeCalculatorMockRecorder
	isgomock struct{}
}

// MockTimeCalculatorMockRecorder is the mock recorder for MockTimeCalculator.
type MockTimeCalculatorMockRecorder struct {
	mock *MockTimeCalculator
}

// NewMockTimeCalculator creates a new mock instance.
func NewMockTimeCalculator(ctrl *gomock.Controller) *MockTimeCalculator {
	mock := &MockTimeCalculator{ctrl: ctrl}
	mock.recorder = &MockTimeCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeCalculator) EXPECT() *MockTimeCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockTimeCalculator) Calculate() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Calculate indicates an expected call of Calculate.
func (mr *MockTimeCalculatorMockRecorder) Calculate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockTimeCalculator)(nil).Calculate))
}

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutor) Execute(ctx context.Context, orderID order.OrderID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), ctx, orderID)
}

// MockdeliveryExecutor is a mock of deliveryExecutor interface.
type MockdeliveryExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryExecutorMockRecorder
	isgomock struct{}
}

// MockdeliveryExecutorMockRecorder is the mock recorder for MockdeliveryExecutor.
type MockdeliveryExecutorMockRecorder struct {
	mock *MockdeliveryExecutor
}

// NewMockdeliveryExecutor creates a new mock instance.
func NewMockdeliveryExecutor(ctrl *gomock.Controller) *MockdeliveryExecutor {
	mock := &MockdeliveryExecutor{ctrl: ctrl}
	mock.recorder = &MockdeliveryExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryExecutor) EXPECT() *MockdeliveryExecutorMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockdeliveryExecutor) Assign(ctx context.Context, orderID order.OrderID) (*delivery.AssignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, orderID)
	ret0, _ := ret[0].(*delivery.AssignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockdeliveryExecutorMockRecorder) Assign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockdeliveryExecutor)(nil).Assign), ctx, orderID)
}

// Complete mocks base method.
func (m *MockdeliveryExecutor) Complete(ctx context.Context, orderID order.OrderID) (*delivery.CompleteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, orderID)
	ret0, _ := ret[0].(*delivery.CompleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockdeliveryExecutorMockRecorder) Complete(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockdeliveryExecutor)(nil).Complete), ctx, orderID)
}

// Unassign mocks base method.
func (m *MockdeliveryExecutor) Unassign(ctx context.Context, orderID order.OrderID) (*delivery.UnassignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", ctx, orderID)
	ret0, _ := ret[0].(*delivery.UnassignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unassign indicates an expected call of Unassign.
func (mr *MockdeliveryExecutorMockRecorder) Unassign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockdeliveryExecutor)(nil).Unassign), ctx, orderID)
}

// MockdeliveryAssign is a mock of deliveryAssign interface.
type MockdeliveryAssign struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryAssignMockRecorder
	isgomock struct{}
}

// MockdeliveryAssignMockRecorder is the mock recorder for MockdeliveryAssign.
type MockdeliveryAssignMockRecorder struct {
	mock *MockdeliveryAssign
}

// NewMockdeliveryAssign creates a new mock instance.
func NewMockdeliveryAssign(ctrl *gomock.Controller) *MockdeliveryAssign {
	mock := &MockdeliveryAssign{ctrl: ctrl}
	mock.recorder = &MockdeliveryAssignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryAssign) EXPECT() *MockdeliveryAssignMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockdeliveryAssign) Assign(ctx context.Context, orderID order.OrderID) (*delivery.AssignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, orderID)
	ret0, _ := ret[0].(*delivery.AssignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockdeliveryAssignMockRecorder) Assign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockdeliveryAssign)(nil).Assign), ctx, orderID)
}

// MockdeliveryUnassign is a mock of deliveryUnassign interface.
type MockdeliveryUnassign struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryUnassignMockRecorder
	isgomock struct{}
}

// MockdeliveryUnassignMockRecorder is the mock recorder for MockdeliveryUnassign.
type MockdeliveryUnassignMockRecorder struct {
	mock *MockdeliveryUnassign
}

// NewMockdeliveryUnassign creates a new mock instance.
func NewMockdeliveryUnassign(ctrl *gomock.Controller) *MockdeliveryUnassign {
	mock := &MockdeliveryUnassign{ctrl: ctrl}
	mock.recorder = &MockdeliveryUnassignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryUnassign) EXPECT() *MockdeliveryUnassignMockRecorder {
	return m.recorder
}

// Unassign mocks base method.
func (m *MockdeliveryUnassign) Unassign(ctx context.Context, orderID order.OrderID) (*delivery.UnassignResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", ctx, orderID)
	ret0, _ := ret[0].(*delivery.UnassignResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unassign indicates an expected call of Unassign.
func (mr *MockdeliveryUnassignMockRecorder) Unassign(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockdeliveryUnassign)(nil).Unassign), ctx, orderID)
}

// MockdeliveryComplete is a mock of deliveryComplete interface.
type MockdeliveryComplete struct {
	ctrl     *gomock.Controller
	recorder *MockdeliveryCompleteMockRecorder
	isgomock struct{}
}

// MockdeliveryCompleteMockRecorder is the mock recorder for MockdeliveryComplete.
type MockdeliveryCompleteMockRecorder struct {
	mock *MockdeliveryComplete
}

// NewMockdeliveryComplete creates a new mock instance.
func NewMockdeliveryComplete(ctrl *gomock.Controller) *MockdeliveryComplete {
	mock := &MockdeliveryComplete{ctrl: ctrl}
	mock.recorder = &MockdeliveryCompleteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeliveryComplete) EXPECT() *MockdeliveryCompleteMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockdeliveryComplete) Complete(ctx context.Context, orderID order.OrderID) (*delivery.CompleteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, orderID)
	ret0, _ := ret[0].(*delivery.CompleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockdeliveryCompleteMockRecorder) Complete(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockdeliveryComplete)(nil).Complete), ctx, orderID)
}
